// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrR22u6O9VDMXjxlC4aL5dw62-SKf-ySk',
    appId: '1:562749050604:web:68281f8b28a3838187dfc9',
    messagingSenderId: '562749050604',
    projectId: 'readee-d562c',
    authDomain: 'readee-d562c.firebaseapp.com',
    storageBucket: 'readee-d562c.firebasestorage.app',
    measurementId: 'G-RPCGWXWF5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJL0_5EmFgrt6sYjm5NlexZw-8Wc9_-nE',
    appId: '1:562749050604:android:61e32312ed13ebd887dfc9',
    messagingSenderId: '562749050604',
    projectId: 'readee-d562c',
    storageBucket: 'readee-d562c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEMSBxNH_GNZvVHyomkEwBvh4if1ifHzo',
    appId: '1:562749050604:ios:49f2b4722bf1886e87dfc9',
    messagingSenderId: '562749050604',
    projectId: 'readee-d562c',
    storageBucket: 'readee-d562c.firebasestorage.app',
    iosBundleId: 'com.example.readeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEMSBxNH_GNZvVHyomkEwBvh4if1ifHzo',
    appId: '1:562749050604:ios:49f2b4722bf1886e87dfc9',
    messagingSenderId: '562749050604',
    projectId: 'readee-d562c',
    storageBucket: 'readee-d562c.firebasestorage.app',
    iosBundleId: 'com.example.readeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrR22u6O9VDMXjxlC4aL5dw62-SKf-ySk',
    appId: '1:562749050604:web:463470f5820e32a387dfc9',
    messagingSenderId: '562749050604',
    projectId: 'readee-d562c',
    authDomain: 'readee-d562c.firebaseapp.com',
    storageBucket: 'readee-d562c.firebasestorage.app',
    measurementId: 'G-9GE3VPQY2M',
  );
}
